# Generated by Django 4.2 on 2026-01-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='category',
            field=models.CharField(choices=[('Resort', 'Resort'), ('Hotel', 'Hotel')], default='Resort', max_length=10),
        ),
    ]
